export const entities = [
  // Existing entities
  {
    role: "warrior",
    types: ["physical", "earth"],
    health: 30,
    shield: 0,
    strengthen: 0,
    aggro: 0,
    effects: [],
    faction: "hero",
    alive: true,
    proficiency: {},
    locked: false,
    power: 1,
    defaultDeck: [
      { cardName: "strike", frequency: 4 },
      { cardName: "bandage", frequency: 2 },
      { cardName: "shield", frequency: 3 },
      { cardName: "disengage", frequency: 2 },
      { cardName: "grapple", frequency: 2 },
      { cardName: "plate armor", frequency: 2 },
      { cardName: "mirror shield", frequency: 2 },
      { cardName: "taunt", frequency: 3 },
    ],
  },
  {
    role: "cleric",
    types: ["light", "nature"],
    health: 15,
    shield: 0,
    strengthen: 0,
    aggro: 0,
    effects: [],
    faction: "hero",
    alive: true,
    proficiency: {},
    locked: false,
    power: 1,
    defaultDeck: [
      { cardName: "rejuvinate", frequency: 3 },
      { cardName: "empower", frequency: 3 },
      { cardName: "weaken", frequency: 3 },
      { cardName: "disengage", frequency: 2 },
      { cardName: "strike", frequency: 3 },
      { cardName: "heal", frequency: 6 },
    ],
  },
  {
    role: "rogue",
    types: ["poison", "dark"],
    health: 20,
    shield: 0,
    strengthen: 0,
    aggro: 0,
    effects: [],
    faction: "hero",
    alive: true,
    proficiency: {},
    locked: false,
    power: 1,
    defaultDeck: [
      { cardName: "poison", frequency: 4 },
      { cardName: "venom blade", frequency: 3 },
      { cardName: "mastermind", frequency: 2 },
      { cardName: "vanish", frequency: 2 },
      { cardName: "strike", frequency: 5 },
      { cardName: "flurry", frequency: 2 },
      { cardName: "explosive poison trap", frequency: 1 },
      { cardName: "paralyzing trap", frequency: 1 },
    ],
  },
  {
    role: "mage",
    types: ["arcane", "fire"],
    health: 15,
    shield: 0,
    strengthen: 0,
    aggro: 0,
    effects: [],
    faction: "hero",
    alive: true,
    proficiency: {},
    locked: false,
    power: 1,
    defaultDeck: [
      { cardName: "strike", frequency: 3 },
      { cardName: "fireball", frequency: 4 },
      { cardName: "freeze", frequency: 4 },
      { cardName: "spell block", frequency: 2 },
      { cardName: "illusion", frequency: 1 },
      { cardName: "disengage", frequency: 4 },
      { cardName: "shield", frequency: 2 },
    ],
  },
  {
    role: "paladin",
    types: ["light", "physical"],
    health: 25,
    shield: 0,
    strengthen: 0,
    aggro: 0,
    effects: [],
    faction: "hero",
    alive: true,
    proficiency: {},
    locked: false,
    power: 1,
    defaultDeck: [
      { cardName: "strike", frequency: 6 },
      { cardName: "selfless sacrifice", frequency: 2 },
      { cardName: "heal", frequency: 4 },
      { cardName: "rejuvinate", frequency: 3 },
      { cardName: "disengage", frequency: 2 },
      { cardName: "grapple", frequency: 3 },
    ],
  },
  {
    role: "druid",
    types: ["nature", "poison"],
    health: 25,
    shield: 0,
    strengthen: 0,
    aggro: 0,
    effects: [],
    faction: "hero",
    alive: true,
    proficiency: {},
    locked: false,
    power: 1,
    defaultDeck: [
      { cardName: "strike", frequency: 3 },
      { cardName: "poison", frequency: 4 },
      { cardName: "heal", frequency: 4 },
      { cardName: "rejuvinate", frequency: 3 },
      { cardName: "disengage", frequency: 3 },
      { cardName: "summon spirit", frequency: 3 },
    ],
  },
  {
    role: "death knight",
    types: ["dark", "frost"],
    health: 25,
    shield: 0,
    strengthen: 0,
    aggro: 0,
    effects: [],
    faction: "hero",
    alive: true,
    proficiency: {},
    locked: false,
    power: 1,
    defaultDeck: [
      { cardName: "strike", frequency: 4 },
      { cardName: "siphon life", frequency: 2 },
      { cardName: "shield", frequency: 2 },
      { cardName: "grapple", frequency: 2 },
      { cardName: "plate armor", frequency: 2 },
      { cardName: "freeze", frequency: 3 },
      { cardName: "taunt", frequency: 5 },
    ],
  },
  {
    role: "bard",
    types: ["arcane", "light"],
    health: 25,
    shield: 0,
    strengthen: 0,
    aggro: 0,
    effects: [],
    faction: "hero",
    alive: true,
    proficiency: {},
    locked: false,
    power: 1,
    defaultDeck: [
      { cardName: "strike", frequency: 4 },
      { cardName: "humiliate", frequency: 2 },
      { cardName: "shield", frequency: 2 },
      { cardName: "healing word", frequency: 2 },
      { cardName: "power chord", frequency: 4 },
      { cardName: "inspiring medley", frequency: 3 },
      { cardName: "cutting remark", frequency: 5 },
    ],
  },
  {
    role: "goblin",
    types: ["physical", "dark"],
    health: 10,
    shield: 0,
    strengthen: 0,
    aggro: 0,
    effects: [],
    faction: "monster",
    alive: true,
    proficiency: {},
    power: 1,
    defaultDeck: [
      { cardName: "slash", frequency: 8 },
      { cardName: "quick attack", frequency: 5 },
      { cardName: "regenerate", frequency: 1 },
    ],
  },
  {
    role: "skeleton",
    types: ["dark", "physical"],
    health: 15,
    shield: 0,
    strengthen: 0,
    aggro: 0,
    effects: [],
    faction: "monster",
    alive: true,
    proficiency: {},
    power: 2,
    defaultDeck: [
      { cardName: "slash", frequency: 8 },
      { cardName: "block", frequency: 6 },
      { cardName: "rend armor", frequency: 5 },
      { cardName: "regenerate", frequency: 1 },
    ],
  },
  {
    role: "vampire",
    types: ["dark", "blood"],
    health: 15,
    shield: 0,
    strengthen: 0,
    aggro: 0,
    effects: [],
    faction: "monster",
    alive: true,
    proficiency: {},
    power: 3,
    defaultDeck: [
      { cardName: "scratch", frequency: 4 },
      { cardName: "vampiric bite", frequency: 10 },
      { cardName: "debilitate", frequency: 4 },
      { cardName: "reconstitute", frequency: 2 },
    ],
  },
  {
    role: "werewolf",
    types: ["dark", "nature"],
    health: 20,
    shield: 0,
    strengthen: 0,
    aggro: 0,
    effects: [],
    faction: "monster",
    alive: true,
    proficiency: {},
    power: 3,
    defaultDeck: [
      { cardName: "strike", frequency: 3 },
      { cardName: "bandage", frequency: 2 },
      { cardName: "shield", frequency: 3 },
      { cardName: "disengage", frequency: 2 },
      { cardName: "lycanthropy", frequency: 10 },
    ],
  },
  {
    role: "orc",
    types: ["physical", "earth"],
    health: 25,
    shield: 0,
    strengthen: 0,
    aggro: 0,
    effects: [],
    faction: "monster",
    alive: true,
    proficiency: {},
    power: 3,
    defaultDeck: [
      { cardName: "scratch", frequency: 3 },
      { cardName: "bite", frequency: 3 },
      { cardName: "swipe", frequency: 3 },
      { cardName: "monster heal", frequency: 1 },
    ],
  },
  {
    role: "ogre",
    types: ["earth", "physical"],
    health: 35,
    shield: 0,
    strengthen: 0,
    aggro: 0,
    effects: [],
    faction: "monster",
    alive: true,
    proficiency: {},
    power: 6,
    defaultDeck: [
      { cardName: "crush", frequency: 8 },
      { cardName: "throw rock", frequency: 6 },
      { cardName: "stomp", frequency: 5 },
      { cardName: "monster heal", frequency: 1 },
    ],
  },
  {
    role: "mindflayer",
    types: ["psychic", "dark"],
    health: 25,
    shield: 0,
    strengthen: 0,
    aggro: 0,
    effects: [],
    faction: "monster",
    alive: true,
    proficiency: {},
    power: 9,
    defaultDeck: [
      { cardName: "mind blast", frequency: 8 },
      { cardName: "psychic scream", frequency: 6 },
      { cardName: "debilitate", frequency: 5 },
      { cardName: "reconstitute", frequency: 1 },
    ],
  },
  {
    role: "dragon",
    types: ["fire", "arcane"],
    health: 50,
    shield: 0,
    strengthen: 0,
    aggro: 0,
    effects: [],
    faction: "monster",
    alive: true,
    proficiency: {},
    power: 12,
    defaultDeck: [
      { cardName: "fire breath", frequency: 8 },
      { cardName: "tail swipe", frequency: 6 },
      { cardName: "wing gust", frequency: 5 },
      { cardName: "fiery regeneration", frequency: 1 },
    ],
  },
  // New entities
  {
    role: "elemental",
    types: ["fire", "earth"],
    health: 20,
    shield: 0,
    strengthen: 0,
    aggro: 0,
    effects: [],
    faction: "monster",
    alive: true,
    proficiency: {},
    power: 4,
    defaultDeck: [
      { cardName: "flame wave", frequency: 4 },
      { cardName: "earthquake", frequency: 4 },
      { cardName: "rock shield", frequency: 3 },
      { cardName: "magma surge", frequency: 3 },
    ],
  },
  {
    role: "necromancer",
    types: ["dark", "arcane"],
    health: 18,
    shield: 0,
    strengthen: 0,
    aggro: 0,
    effects: [],
    faction: "hero",
    alive: true,
    proficiency: {},
    power: 6,
    defaultDeck: [
      { cardName: "dark reaping", frequency: 4 },
      { cardName: "summon skeleton", frequency: 3 },
      { cardName: "arcane barrier", frequency: 3 },
      { cardName: "soul drain", frequency: 4 },
    ],
  },
  {
    role: "phoenix",
    types: ["fire", "light"],
    health: 22,
    shield: 0,
    strengthen: 0,
    aggro: 0,
    effects: [],
    faction: "monster",
    alive: true,
    proficiency: {},
    power: 5,
    defaultDeck: [
      { cardName: "phoenix flame", frequency: 4 },
      { cardName: "rebirth", frequency: 2 },
      { cardName: "blazing aura", frequency: 4 },
      { cardName: "healing flame", frequency: 2 },
    ],
  },
  {
    role: "shaman",
    types: ["nature", "psychic"],
    health: 20,
    shield: 0,
    strengthen: 0,
    aggro: 0,
    effects: [],
    faction: "hero",
    alive: true,
    proficiency: {},
    locked: false,
    power: 2,
    defaultDeck: [
      { cardName: "spirit link", frequency: 4 },
      { cardName: "healing rain", frequency: 3 },
      { cardName: "totem summon", frequency: 3 },
      { cardName: "mind cleanse", frequency: 3 },
      { cardName: "strike", frequency: 3 },
      { cardName: "disengage", frequency: 3 },
    ],
  },
  {
    role: "berserker",
    types: ["physical", "blood"],
    health: 28,
    shield: 0,
    strengthen: 0,
    aggro: 0,
    effects: [],
    faction: "hero",
    alive: true,
    proficiency: {},
    locked: false,
    power: 3,
    defaultDeck: [
      { cardName: "frenzy", frequency: 4 },
      { cardName: "blood rage", frequency: 4 },
      { cardName: "reckless strike", frequency: 4 },
      { cardName: "self-heal", frequency: 2 },
    ],
  },
];
