export const instance = [
    {id: 1, level: 1, monsters:['goblin'], monsterImage: '../../images/goblin.png'},
    {id: 2, level: 1, monsters:['goblin'], monsterImage: '../../images/goblin.png'},
    {id: 3, level: 2, monsters:['skeleton'], monsterImage: '../../images/skeleton.png'},
    {id: 4, level: 2, monsters:['skeleton'], monsterImage: '../../images/skeleton.png'},
    {id: 5, level: 3, monsters:['goblin', 'orc'], monsterImage: '../../images/orc.png'},
    {id: 6, level: 3, monsters:['goblin', 'orc'], monsterImage: '../../images/orc.png'},
    {id: 7, level: 4, monsters:['werewolf'], monsterImage: '../../images/werewolf.png'},
    {id: 8, level: 4, monsters:['werewolf'], monsterImage: '../../images/werewolf.png'},
    {id: 9, level: 5, monsters:['skeleton', 'vampire'], monsterImage: '../../images/vampire.png'},
    {id: 10, level: 5, monsters:['skeleton', 'vampire'], monsterImage: '../../images/vampire.png'},
    {id: 11, level: 6, monsters:['vampire'], monsterImage: '../../images/vampire.png'},
    {id: 12, level: 6, monsters:['vampire'], monsterImage: '../../images/vampire.png'},
    {id: 13, level: 7, monsters:['mindflayer'], monsterImage: '../../images/mindflayer.png'},
    {id: 14, level: 7, monsters:['mindflayer'], monsterImage: '../../images/mindflayer.png'},
    {id: 15, level: 8, monsters:['orc', 'ogre'], monsterImage: '../../images/ogre.png'},
    {id: 16, level: 8, monsters:['orc', 'ogre'], monsterImage: '../../images/ogre.png'},
    {id: 17, level: 9, monsters:['ogre'], monsterImage: '../../images/ogre.png'},
    {id: 18, level: 9, monsters:['ogre'], monsterImage: '../../images/ogre.png'},
    {id: 19, level: 10, monsters:['dragon'], monsterImage: '../../images/dragon.png'},
    {id: 20, level: 10, monsters:['dragon'], monsterImage: '../../images/dragon.png'},
]